# NUMPY
- Numerical Python
- 산술 계산을 위한 패키지
 - 다차원 배열인 ndarray는 빠른 배열 계산을 제공
 - 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수
 - 선형대수, 난수 생성기, 푸리에 변환 가능
- 일반적인 산술 데이터 처리를 위한 기본 라이브러리를 제공
 - 연산 처리 후 통계나 분석 데이터를 처리하기 위해선 Pandas를 사용
- 파이썬 산술 계산 영역에서 중요한 위치를 차지하는 이유 중 하나는 대용량 데이터 배열을 효율적으로 다룰 수 있도록 설계되어 있기 때문

### Numpy 사용 예제

In [2]:
import numpy as np

my_arr = np.arange(100)
my_list = list(range(100))

- 1차원 배열 생성

In [4]:
print(type(my_arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [5]:
print(my_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [6]:
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


- 배열 연산이 for문의 연산 속도보다 더 빠름

### 다차원 배열 객체
- Numpy는 ndarray라고 하는 N차원 배열  객체를 사용
 - 1차원: Vectors
 - 2차원: Martices
 - 3차원: Tensors

### 2 X 3 배열을 랜덤 생성 예제(가우시안 분포 사용)

In [12]:
data = np.random.randn(2,3)
print(data)

[[ 1.49533918  2.24863289 -1.56493354]
 [-2.12707124  0.26572421 -1.51314877]]


### ndarray 생성하기 예제(list ->array)

In [10]:
data1 = [5, 7, 8, 1, 4]

In [11]:
type(data1)

list

In [13]:
arr1 = np.array(data1)

In [14]:
type(arr1)

numpy.ndarray

In [15]:
print(arr1)

[5 7 8 1 4]


### 2차원 배열 생성 예제

In [17]:
arr1 = np.array([[1,2,3],
                [4,5,6]])

In [18]:
print(arr1)

[[1 2 3]
 [4 5 6]]


### numpy 배열의 산술 연산
- numpy 배열은 반복문을 작성하지 않고 데이터를 일괄 처리할 수 있음
 - "벡터화"라고 부름

In [19]:
arr1 = np.array([[1,2,3],
                [4,5,6]])

In [20]:
# 요소곱
print(arr1 * arr1)

[[ 1  4  9]
 [16 25 36]]


In [21]:
# 요소합
print(arr1 + arr1)

[[ 2  4  6]
 [ 8 10 12]]


In [22]:
# 나눗셈
print(1 / arr1)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [23]:
print(arr1 >= arr1)

[[ True  True  True]
 [ True  True  True]]


In [24]:
# 행렬곱
print(np.dot(arr1, np.transpose(arr1)))

[[14 32]
 [32 77]]


### 배열 인덱싱과 슬라이싱
- numpy 배열은 순차적(sequential) 데이터이기 때문에 인덱싱과 슬라이싱 가능

In [25]:
arr1 = np.arange(10)

In [26]:
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
print(arr1[5])

5


In [28]:
print(arr1[5:8])

[5 6 7]


### 다차원 배열 객체 연산
- 브로드캐스팅되어 연산됨

In [30]:
# 1 X 3 배열 + 정수
print(np.arange(3) + 5)

[5 6 7]


In [33]:
# 3 X 1 배열 + 1 X 3 배열
print(np.arange(3).reshape(3,1) + np.arange(3))

[[0 1 2]
 [1 2 3]
 [2 3 4]]


### 배열 행과 열 바꾸기
- np.transpose() or np.T 사용

In [34]:
arr = np.arange(15).reshape(3, 5)

In [35]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [36]:
print(arr.transpose())

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [37]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


np.transpose(np.array([[0,1,2]]))
- 2차원 배열이기 때문에 전치와 축 바꾸기 가능

np.transpose(np.arange(3)), type(np.arange(3)))
- 1차원 배열은 전치와 축 바꾸기 불가능

In [43]:
np.transpose(np.array([[0,1,2]]))

array([[0],
       [1],
       [2]])

In [39]:
np.transpose(np.arange(3)), type(np.arange(3)))

SyntaxError: unmatched ')' (Temp/ipykernel_3328/2423615986.py, line 1)

### 3차원 배열 만들기

In [40]:
arr = np.array([[[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]],
                [[11, 12, 13, 14],
                 [15, 16, 17, 18],
                 [19, 20, 21, 22]]])

In [41]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
